/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Building2, IndianRupee, Mail, MapPin, Search, Target } from 'lucide-react';

const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);

export default function ClientsView() {
  const navigate = useNavigate();
  const [rows, setRows] = useState<any[]>([]), [query, setQuery] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState('');
  useEffect(() => { supabase.from('company_rollup' as any).select('*').order('total_expected_revenue', { ascending: false }).then(({ data, error: loadError }) => { setRows(data || []); setError(loadError?.message || ''); setLoading(false); }); }, []);
  const clients = useMemo(() => rows.filter(row => `${row.name} ${row.email || ''} ${row.industry || ''} ${row.city || ''}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  return <div className="min-h-full bg-slate-50/60 p-4 md:p-7"><p className="text-xs font-bold tracking-wider text-primary">CUSTOMER INTELLIGENCE</p><h1 className="text-3xl font-bold mt-1">Client 360</h1><p className="text-muted-foreground mb-6">Persistent accounts with lifetime pipeline and collections</p><div className="relative mb-5"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9 bg-white" placeholder="Search company, email, industry or city" value={query} onChange={event => setQuery(event.target.value)} /></div>{loading ? <div className="grid lg:grid-cols-2 gap-3">{[1, 2, 3, 4].map(key => <div key={key} className="h-44 bg-white animate-pulse rounded-2xl" />)}</div> : error ? <div className="rounded-2xl bg-amber-50 p-8 text-amber-800">Deploy the companies migration: {error}</div> : <div className="grid xl:grid-cols-2 gap-3">{clients.map(company => <Card key={company.id} onClick={() => navigate(`/clients/${company.id}`)} className="border-0 shadow-sm hover:shadow-md cursor-pointer"><CardContent className="p-5"><div className="flex gap-3"><div className="h-11 w-11 rounded-xl bg-primary/10 text-primary flex items-center justify-center"><Building2 className="h-5 w-5" /></div><div className="flex-1 min-w-0"><div className="flex justify-between gap-3"><div><h3 className="font-bold truncate">{company.name}</h3><p className="text-sm text-muted-foreground">{company.industry || 'Industry not set'}</p></div><Badge>{company.open_opportunity_count} open</Badge></div><div className="grid sm:grid-cols-2 gap-2 mt-4 text-xs text-muted-foreground"><span className="flex items-center"><Mail className="h-3 w-3 mr-1.5" />{company.email || 'No email'}</span><span className="flex items-center"><MapPin className="h-3 w-3 mr-1.5" />{[company.city, company.state].filter(Boolean).join(', ') || 'Location not set'}</span><span className="flex items-center"><Target className="h-3 w-3 mr-1.5" />{company.opportunity_count} opportunities</span><span className="flex items-center"><IndianRupee className="h-3 w-3 mr-1.5" />{money(company.outstanding_amount)} outstanding</span></div><div className="flex justify-between mt-4 pt-3 border-t"><span className="text-xs text-muted-foreground">Weighted pipeline</span><strong>{money(company.total_expected_revenue)}</strong></div></div></div></CardContent></Card>)}{!clients.length && <div className="xl:col-span-2 rounded-2xl bg-white py-20 text-center text-muted-foreground">No company accounts found.</div>}</div>}</div>;
}
