/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ArrowUpRight, Banknote, CalendarClock, CheckCircle2, CircleDollarSign, RefreshCw, Search, TriangleAlert, UserRoundCheck, WalletCards } from 'lucide-react';

const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const today = () => new Date().toISOString().slice(0, 10);
const daysFromToday = (value?: string | null) => value ? Math.ceil((new Date(value).getTime() - new Date(today()).getTime()) / 86400000) : null;

export default function CollectionDashboard() {
  const { toast } = useToast(); const navigate = useNavigate();
  const [rows, setRows] = useState<any[]>([]), [query, setQuery] = useState(''), [filter, setFilter] = useState('action'), [loading, setLoading] = useState(true), [savingId, setSavingId] = useState('');
  const load = () => { setLoading(true); return supabase.from('b2g_collection_dashboard' as any).select('*').then(({ data, error }) => { if (error) toast({ title: 'Collections could not load', description: error.message, variant: 'destructive' }); setRows(data || []); setLoading(false); }); };
  useEffect(() => { load(); }, []);
  const updateMilestone = async (id: string, patch: any) => { setSavingId(id); const { error } = await supabase.from('b2g_payment_milestones' as any).update(patch).eq('id', id); setSavingId(''); if (error) toast({ title: 'Update failed', description: error.message, variant: 'destructive' }); else { toast({ title: 'Collection record updated' }); load(); } };
  const updateProject = async (id: string, work_completed: string) => { setSavingId(id); const { error } = await supabase.from('b2g_projects' as any).update({ work_completed, work_completed_at: work_completed === 'completed' ? today() : null }).eq('id', id); setSavingId(''); if (error) toast({ title: 'Update failed', description: error.message, variant: 'destructive' }); else load(); };

  const enriched = useMemo(() => rows.map(row => { const balance = Number(row.balance_outstanding || 0), invoice = Number(row.invoice_amount || 0), received = Number(row.amount_received || 0), escalationDays = daysFromToday(row.next_escalation_date), dueDays = daysFromToday(row.due_date); const paid = balance <= 0; const escalationDue = !paid && escalationDays !== null && escalationDays <= 0; const overdue = !paid && dueDays !== null && dueDays < 0; return { ...row, balance, invoice, received, paid, escalationDue, overdue, escalationDays, dueDays, collectionPct: invoice > 0 ? Math.min(100, Math.round(received * 100 / invoice)) : 0 }; }).sort((a, b) => Number(b.escalationDue) - Number(a.escalationDue) || Number(b.overdue) - Number(a.overdue) || b.balance - a.balance), [rows]);
  const list = enriched.filter(row => `${row.client} ${row.person_responsible || ''} ${row.last_commitment || ''}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'action' && !row.paid) || (filter === 'overdue' && row.overdue) || (filter === 'escalation' && row.escalationDue) || (filter === 'paid' && row.paid)));
  const stats = useMemo(() => ({ invoice: enriched.reduce((sum, row) => sum + row.invoice, 0), received: enriched.reduce((sum, row) => sum + row.received, 0), balance: enriched.reduce((sum, row) => sum + row.balance, 0), escalations: enriched.filter(row => row.escalationDue).length, pct: enriched.reduce((sum, row) => sum + row.invoice, 0) > 0 ? Math.round(enriched.reduce((sum, row) => sum + row.received, 0) * 100 / enriched.reduce((sum, row) => sum + row.invoice, 0)) : 0 }), [enriched]);

  return <div className="min-h-full bg-slate-50/60 p-4 pb-28 md:p-7 space-y-5">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-wider text-primary">COLLECTION CONTROL</p><h1 className="text-3xl font-bold mt-1">Collection dashboard</h1><p className="text-muted-foreground">Prioritized receivables, ownership, commitments and escalation</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><Button className="w-full" variant="outline" onClick={load}><RefreshCw className="h-4 w-4 mr-2" />Refresh</Button><Button className="w-full" onClick={() => navigate('/growth')}><Banknote className="h-4 w-4 mr-2" />Record receipt</Button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric icon={WalletCards} label="Total invoiced" value={money(stats.invoice)} note={`${stats.pct}% collected`} tone="indigo" /><Metric icon={Banknote} label="Amount received" value={money(stats.received)} note="Receipts posted" tone="emerald" /><Metric icon={TriangleAlert} label="Balance outstanding" value={money(stats.balance)} note={`${enriched.filter(row => !row.paid).length} open items`} tone="rose" /><Metric icon={CalendarClock} label="Escalations due" value={String(stats.escalations)} note="Today or overdue" tone="amber" /></div>
    <Card className="border-0 shadow-sm"><CardContent className="p-4"><div className="flex justify-between text-sm mb-2"><span className="font-semibold">Overall collection progress</span><span>{stats.pct}%</span></div><Progress value={stats.pct} className="h-2" /></CardContent></Card>
    <div className="flex flex-col lg:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9 bg-white" placeholder="Search client, owner or commitment" value={query} onChange={event => setQuery(event.target.value)} /></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="lg:w-52 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="action">Open collections</SelectItem><SelectItem value="escalation">Escalations due</SelectItem><SelectItem value="overdue">Invoice overdue</SelectItem><SelectItem value="paid">Fully collected</SelectItem><SelectItem value="all">All records</SelectItem></SelectContent></Select></div>
    {loading ? <div className="h-72 rounded-2xl bg-white animate-pulse" /> : <>
      <div className="hidden xl:block rounded-2xl bg-white shadow-sm overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Client / invoice</TableHead><TableHead>Work status</TableHead><TableHead className="text-right">Invoice</TableHead><TableHead className="text-right">Received</TableHead><TableHead className="text-right">Outstanding</TableHead><TableHead>Responsible</TableHead><TableHead>Last commitment</TableHead><TableHead>Next escalation</TableHead></TableRow></TableHeader><TableBody>{list.map(row => <TableRow key={row.milestone_id} className={row.escalationDue ? 'bg-rose-50/60' : ''}><TableCell><ClientCell row={row} /></TableCell><TableCell><WorkStatus row={row} save={updateProject} /></TableCell><TableCell className="text-right font-medium">{money(row.invoice)}</TableCell><TableCell className="text-right text-emerald-700 font-medium">{money(row.received)}</TableCell><TableCell className="text-right"><strong className={row.balance > 0 ? 'text-rose-700' : 'text-emerald-700'}>{money(row.balance)}</strong><Progress value={row.collectionPct} className="h-1 mt-2" /></TableCell><TableCell><InlineText value={row.person_responsible} placeholder="Assign owner" save={value => updateMilestone(row.milestone_id, { responsible_person: value })} /></TableCell><TableCell><InlineText value={row.last_commitment} placeholder="Add commitment" save={value => updateMilestone(row.milestone_id, { last_commitment: value })} /></TableCell><TableCell><Escalation row={row} save={value => updateMilestone(row.milestone_id, { next_escalation_date: value })} /></TableCell></TableRow>)}</TableBody></Table></div>
      <div className="xl:hidden space-y-3">{list.map(row => <Card key={row.milestone_id} className={`border-0 shadow-sm ${row.escalationDue ? 'ring-1 ring-rose-300' : ''}`}><CardContent className="p-4 sm:p-5"><ClientCell row={row} /><div className="grid grid-cols-1 min-[360px]:grid-cols-3 gap-2 mt-4"><Amount label="Invoice" value={row.invoice} /><Amount label="Received" value={row.received} positive /><Amount label="Balance" value={row.balance} danger={row.balance > 0} /></div><Progress value={row.collectionPct} className="h-1.5 mt-3" /><p className="text-[11px] text-muted-foreground text-right mt-1">{row.collectionPct}% collected</p><div className="grid sm:grid-cols-2 gap-3 mt-4"><Field label="Work status"><WorkStatus row={row} save={updateProject} /></Field><Field label="Person responsible"><InlineText value={row.person_responsible} placeholder="Assign owner" save={value => updateMilestone(row.milestone_id, { responsible_person: value })} /></Field><Field label="Last commitment"><InlineText value={row.last_commitment} placeholder="Add commitment" save={value => updateMilestone(row.milestone_id, { last_commitment: value })} /></Field><Field label="Next escalation"><Escalation row={row} save={value => updateMilestone(row.milestone_id, { next_escalation_date: value })} /></Field></div>{savingId === row.milestone_id && <p className="text-xs text-primary mt-3">Saving…</p>}</CardContent></Card>)}</div>
      {!list.length && <div className="rounded-2xl bg-white py-20 text-center"><CheckCircle2 className="h-10 w-10 mx-auto text-emerald-500 mb-3" /><h3 className="font-bold">No matching collections</h3><p className="text-sm text-muted-foreground mt-1">Change the filter or create project payment milestones.</p></div>}
    </>}
  </div>;
}

function ClientCell({ row }: { row: any }) { return <div><div className="flex items-center gap-2"><p className="font-bold">{row.client}</p>{row.paid ? <Badge className="bg-emerald-100 text-emerald-700">Paid</Badge> : row.escalationDue ? <Badge variant="destructive">Escalate</Badge> : row.overdue ? <Badge className="bg-amber-100 text-amber-700">Overdue</Badge> : <Badge variant="secondary">Open</Badge>}</div><p className="text-xs font-medium mt-1">Order: {row.project_name || 'Unnamed project'}</p><p className="text-xs text-muted-foreground">{row.invoice_number || 'Invoice number pending'} · due {row.due_date ? new Date(row.due_date).toLocaleDateString('en-IN') : 'not set'}</p></div>; }
function WorkStatus({ row, save }: { row: any; save: (id: string, value: string) => void }) { const value = ['pending', 'in_progress', 'completed'].includes(row.work_completed) ? row.work_completed : row.work_completed ? 'completed' : 'pending'; return <Select value={value} onValueChange={next => save(row.project_id, next)}><SelectTrigger className="min-w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="pending">Pending</SelectItem><SelectItem value="in_progress">In progress</SelectItem><SelectItem value="completed">Completed</SelectItem></SelectContent></Select>; }
function InlineText({ value, placeholder, save }: { value?: string; placeholder: string; save: (value: string | null) => void }) { return <Input className="min-w-36" defaultValue={value || ''} placeholder={placeholder} onBlur={event => { const next = event.target.value.trim() || null; if (next !== (value || null)) save(next); }} />; }
function Escalation({ row, save }: { row: any; save: (value: string | null) => void }) { return <div><Input type="date" className={row.escalationDue ? 'border-rose-400 text-rose-700' : ''} defaultValue={row.next_escalation_date || ''} onBlur={event => save(event.target.value || null)} />{row.next_escalation_date && <p className={`text-[10px] mt-1 ${row.escalationDue ? 'text-rose-600 font-semibold' : 'text-muted-foreground'}`}>{row.escalationDue ? `${Math.abs(row.escalationDays)} day(s) overdue` : `in ${row.escalationDays} day(s)`}</p>}</div>; }
function Metric({ icon: Icon, label, value, note, tone }: any) { const colors: any = { indigo: 'bg-indigo-50 text-indigo-600', emerald: 'bg-emerald-50 text-emerald-600', rose: 'bg-rose-50 text-rose-600', amber: 'bg-amber-50 text-amber-600' }; return <Card className="border-0 shadow-sm"><CardContent className="p-4"><div className={`h-9 w-9 rounded-xl flex items-center justify-center ${colors[tone]}`}><Icon className="h-4 w-4" /></div><p className="text-lg md:text-xl font-extrabold mt-4 break-words">{value}</p><p className="text-xs text-muted-foreground">{label}</p><p className="text-[10px] text-muted-foreground mt-1">{note}</p></CardContent></Card>; }
function Amount({ label, value, positive, danger }: any) { return <div className="rounded-xl bg-slate-50 p-3"><p className={`font-bold text-sm ${positive ? 'text-emerald-700' : danger ? 'text-rose-700' : ''}`}>{money(value)}</p><p className="text-[10px] text-muted-foreground">{label}</p></div>; }
function Field({ label, children }: any) { return <label><span className="text-xs text-muted-foreground flex items-center gap-1"><UserRoundCheck className="h-3 w-3" />{label}</span><div className="mt-1">{children}</div></label>; }
