import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import MarginAnalytics from '@/pages/MarginAnalytics';
import { ArrowRight, BadgeIndianRupee, BrainCircuit, CalendarClock, Flame, Target, TrendingUp, Users } from 'lucide-react';

type Lead = { id:string; organization_name:string; contact_name:string; pipeline:string; stage:string; heat:string; ai_score:number; proposal_value:number; expected_revenue:number; next_follow_up_at:string|null; next_best_action:string|null; assigned_to:string|null };
type Payment = { amount:number; gst_amount:number; amount_received:number; due_date:string|null; status:string };
type TeamProfile = { user_id:string; full_name:string|null };
type FollowUpTask = { id:string; lead_id:string|null; due_at:string; completed_at:string|null };
const money = (n:number) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
const pipelineLabel:Record<string,string> = { brand_approval:'Brand Approval', government_business_development:'Govt. Business Development', tender_consultancy:'Tender Consultancy' };
const pipelineColor:Record<string,string> = { brand_approval:'bg-indigo-500', government_business_development:'bg-emerald-500', tender_consultancy:'bg-amber-500' };

export default function Dashboard(){
  const { profile, user } = useAuth(); const navigate=useNavigate();
  const [leads,setLeads]=useState<Lead[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [profiles,setProfiles]=useState<TeamProfile[]>([]); const [tasks,setTasks]=useState<FollowUpTask[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{ (async()=>{ const [l,p,t,f]=await Promise.all([
    supabase.from('b2g_leads' as any).select('id,organization_name,contact_name,pipeline,stage,heat,ai_score,proposal_value,expected_revenue,next_follow_up_at,next_best_action,assigned_to').order('created_at',{ascending:false}),
    supabase.from('b2g_payment_milestones' as any).select('amount,gst_amount,amount_received,due_date,status'),
    supabase.from('profiles').select('user_id,full_name'),
    supabase.from('b2g_tasks' as any).select('id,lead_id,due_at,completed_at').eq('task_type','follow_up').is('completed_at',null)
  ]); await supabase.rpc('refresh_b2g_escalations' as any); setLeads((l.data||[]) as unknown as Lead[]); setPayments((p.data||[]) as unknown as Payment[]); setProfiles((t.data||[]) as TeamProfile[]); setTasks((f.data||[]) as unknown as FollowUpTask[]); setLoading(false); })(); },[]);
  const today=new Date().toISOString().slice(0,10);
  const stats=useMemo(()=>({ active:leads.filter(l=>!['closed','completed','final_payment_received'].includes(l.stage)).length, hot:leads.filter(l=>l.heat==='hot').length, followups:leads.filter(l=>l.next_follow_up_at?.slice(0,10)===today).length, overdue:tasks.filter(task=>task.due_at.slice(0,10)<today).length, proposal:leads.reduce((a,l)=>a+Number(l.proposal_value),0), expected:leads.reduce((a,l)=>a+Number(l.expected_revenue),0), outstanding:payments.reduce((a,p)=>a+Math.max(0,Number(p.amount)+Number(p.gst_amount)-Number(p.amount_received)),0), collected:payments.reduce((a,p)=>a+Number(p.amount_received),0) }),[leads,payments,tasks,today]);
  const priority=[...leads].filter(l=>l.heat==='hot'||l.ai_score>=70||(l.next_follow_up_at?.slice(0,10)||'9999')<=today).sort((a,b)=>b.ai_score-a.ai_score).slice(0,5);
  const upcomingFollowups=[...leads].filter(l=>l.next_follow_up_at&&!['closed','completed','final_payment_received'].includes(l.stage)).sort((a,b)=>new Date(a.next_follow_up_at!).getTime()-new Date(b.next_follow_up_at!).getTime()).slice(0,8);
  const indiaHour=Number(new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',hour12:false}).format(new Date()));
  const greeting=indiaHour<12?'Good morning':indiaHour<17?'Good afternoon':'Good evening';
  const displayName=profile?.full_name||user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Team';
  const pipelines=Object.keys(pipelineLabel).map(key=>({key,count:leads.filter(l=>l.pipeline===key).length,value:leads.filter(l=>l.pipeline===key).reduce((a,l)=>a+Number(l.proposal_value),0)}));
  const teamPerformance=profiles.map(p=>({name:p.full_name||'Team member',leads:leads.filter(l=>l.assigned_to===p.user_id).length,value:leads.filter(l=>l.assigned_to===p.user_id).reduce((a,l)=>a+Number(l.proposal_value),0)})).filter(p=>p.leads).sort((a,b)=>b.value-a.value);
  const cards=[{label:'Total Active Leads',value:String(stats.active),icon:Users,color:'text-blue-600',bg:'bg-blue-50'},{label:'Hot Leads',value:String(stats.hot),icon:Flame,color:'text-rose-600',bg:'bg-rose-50'},{label:"Today's Follow-ups",value:String(stats.followups),icon:CalendarClock,color:'text-violet-600',bg:'bg-violet-50'},{label:'Overdue Follow-ups',value:String(stats.overdue),icon:CalendarClock,color:'text-rose-600',bg:'bg-rose-50'},{label:'Proposal Value',value:money(stats.proposal),icon:Target,color:'text-indigo-600',bg:'bg-indigo-50'},{label:'Revenue Closed',value:money(stats.collected),icon:TrendingUp,color:'text-emerald-600',bg:'bg-emerald-50'},{label:'Outstanding Collections',value:money(stats.outstanding),icon:BadgeIndianRupee,color:'text-amber-600',bg:'bg-amber-50'}];
  return <div className="min-h-full bg-slate-50/60 p-4 md:p-7 space-y-6">
    <div><div className="flex items-center gap-2 text-primary font-bold text-sm"><img src="/tenderexpert-logo-hd.png" alt="TenderExpert" className="h-8 w-8 rounded-full object-cover"/> TENDEREXPERT</div><h1 className="text-2xl md:text-3xl font-bold mt-2">{greeting}, {displayName.split(' ')[0]}</h1><p className="text-muted-foreground mt-1">Your B2G business command centre</p></div>
    {loading?<div className="grid md:grid-cols-3 gap-3">{[1,2,3,4,5,6].map(x=><div key={x} className="h-28 bg-white rounded-2xl animate-pulse"/>)}</div>:<>
      <div className="grid grid-cols-2 lg:grid-cols-4 xl:grid-cols-7 gap-3">{cards.map(c=><Card key={c.label} className="min-w-0 border-0 shadow-sm"><CardContent className="p-3 sm:p-4"><div className={`h-9 w-9 rounded-xl ${c.bg} ${c.color} flex items-center justify-center mb-4`}><c.icon className="h-4 w-4"/></div><p className="break-words text-base sm:text-xl font-extrabold tracking-tight">{c.value}</p><p className="text-xs text-muted-foreground mt-1">{c.label}</p></CardContent></Card>)}</div>
      <div className="grid lg:grid-cols-5 gap-5"><Card className="lg:col-span-3 border-0 shadow-sm"><CardContent className="p-5"><div className="flex items-center justify-between mb-5"><div><h2 className="font-bold text-lg">Business pipelines</h2><p className="text-xs text-muted-foreground">Live opportunity volume and value</p></div><Button variant="ghost" size="sm" onClick={()=>navigate('/leads')}>View all <ArrowRight className="h-3 w-3 ml-1"/></Button></div><div className="space-y-5">{pipelines.map(p=>{const pct=leads.length?Math.round(p.count/leads.length*100):0;return <button key={p.key} onClick={()=>navigate(`/leads?pipeline=${p.key}`)} className="w-full text-left"><div className="flex justify-between text-sm mb-2"><span className="font-semibold">{pipelineLabel[p.key]}</span><span className="text-muted-foreground">{p.count} leads · {money(p.value)}</span></div><div className="h-2.5 bg-slate-100 rounded-full overflow-hidden"><div className={`h-full ${pipelineColor[p.key]} rounded-full`} style={{width:`${Math.max(pct,p.count?5:0)}%`}}/></div></button>})}</div></CardContent></Card>
      <Card className="lg:col-span-2 border-0 shadow-sm bg-slate-950 text-white"><CardContent className="p-5"><div className="flex items-center gap-2"><BrainCircuit className="h-5 w-5 text-cyan-400"/><h2 className="font-bold text-lg">AI action desk</h2></div><p className="text-xs text-slate-400 mt-1 mb-4">Prioritized by heat, score and follow-up</p><div className="space-y-2">{priority.length?priority.map(l=><button key={l.id} onClick={()=>navigate(`/leads/${l.id}`)} className="w-full p-3 rounded-xl bg-white/5 hover:bg-white/10 text-left"><div className="flex justify-between gap-2"><span className="text-sm font-semibold truncate">{l.organization_name}</span><Badge className="bg-cyan-400/15 text-cyan-300 border-0">{l.ai_score}</Badge></div><p className="text-xs text-slate-400 mt-1 truncate">{l.next_best_action||'Schedule the next decision-maker follow-up'}</p></button>):<p className="text-sm text-slate-400 py-8 text-center">Priority actions will appear here.</p>}</div></CardContent></Card></div>
      <Card className="border-0 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between gap-3 mb-4"><div><div className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-primary"/><h2 className="font-bold text-lg">Next follow-ups</h2></div><p className="text-xs text-muted-foreground mt-1">Upcoming client conversations and reminders</p></div><Button variant="ghost" size="sm" onClick={()=>navigate('/tasks')}>View tasks <ArrowRight className="h-3 w-3 ml-1"/></Button></div><div className="grid md:grid-cols-2 gap-3">{upcomingFollowups.map(lead=>{const dueAt=new Date(lead.next_follow_up_at!),overdue=dueAt<new Date(),withinDay=!overdue&&dueAt.getTime()-Date.now()<=86400000;return <button key={lead.id} onClick={()=>navigate(`/leads/${lead.id}`)} className={`rounded-xl border p-3 text-left transition-colors hover:bg-muted/50 ${overdue?'border-rose-200 bg-rose-50/50':withinDay?'border-amber-200 bg-amber-50/50':'border-border/50'}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="font-semibold truncate">{lead.organization_name}</p><p className="text-xs text-muted-foreground truncate">{lead.contact_name||'Client contact'}</p></div><Badge variant={overdue?'destructive':'secondary'}>{overdue?'Overdue':withinDay?'Within 1 day':'Upcoming'}</Badge></div><p className="text-sm font-medium mt-3">{dueAt.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</p>{lead.next_best_action&&<p className="text-xs text-muted-foreground mt-1 truncate">{lead.next_best_action}</p>}</button>})}{!upcomingFollowups.length&&<p className="text-sm text-muted-foreground py-6 text-center md:col-span-2">No upcoming follow-ups. Add a follow-up date when creating or updating a lead.</p>}</div></CardContent></Card>
      <Card className="border-0 shadow-sm"><CardContent className="p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">Collections overview</p><p className="text-2xl font-extrabold mt-1">{money(stats.collected)} collected</p><p className="text-sm text-muted-foreground">{money(stats.outstanding)} pending across active milestones</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>navigate('/orders')}>Payments</Button><Button onClick={()=>navigate('/leads')}>Open pipeline</Button></div></CardContent></Card>
      <MarginAnalytics embedded />
    </>}
  </div>
}
