alter table public.proforma_invoices
  add column if not exists project_name text,
  add column if not exists po_number text,
  add column if not exists po_date date,
  add column if not exists tender_id text,
  add column if not exists contract_number text,
  add column if not exists hsn_sac_code text,
  add column if not exists place_of_supply text,
  add column if not exists cgst_amount numeric(14,2) not null default 0,
  add column if not exists sgst_amount numeric(14,2) not null default 0,
  add column if not exists igst_amount numeric(14,2) not null default 0,
  add column if not exists tds_amount numeric(14,2) not null default 0,
  add column if not exists retention_amount numeric(14,2) not null default 0,
  add column if not exists advance_adjustment numeric(14,2) not null default 0,
  add column if not exists amount_in_words text,
  add column if not exists payment_terms text,
  add column if not exists submitted_at timestamptz,
  add column if not exists paid_at timestamptz,
  add column if not exists utr_number text;
alter table public.tax_invoices
  add column if not exists project_name text,
  add column if not exists po_number text,
  add column if not exists po_date date,
  add column if not exists tender_id text,
  add column if not exists contract_number text,
  add column if not exists hsn_sac_code text,
  add column if not exists place_of_supply text,
  add column if not exists cgst_amount numeric(14,2) not null default 0,
  add column if not exists sgst_amount numeric(14,2) not null default 0,
  add column if not exists igst_amount numeric(14,2) not null default 0,
  add column if not exists tds_amount numeric(14,2) not null default 0,
  add column if not exists retention_amount numeric(14,2) not null default 0,
  add column if not exists advance_adjustment numeric(14,2) not null default 0,
  add column if not exists amount_in_words text,
  add column if not exists payment_terms text,
  add column if not exists submitted_at timestamptz,
  add column if not exists paid_at timestamptz,
  add column if not exists utr_number text;
